import 'user_class.dart';

List<User> userList = [
  User(
    name: 'John Doe',
    gender: 'Male',
    dob: '1990-01-01',
    maritalStatus: 'Single',
    country: 'USA',
    state: 'California',
    city: 'Los Angeles',
    religion: 'Christian',
    caste: 'General',
    subCaste: 'N/A',
    education: 'Bachelors',
    occupation: 'Engineer',
    email: 'john.doe@example.com',
    phone: '1234567890',
    isFavorite: false,
  ),
  User(
    name: 'William Alexander',
    gender: 'Female',
    dob: '1985-05-15',
    maritalStatus: 'Married',
    country: 'Canada',
    state: 'Ontario',
    city: 'Toronto',
    religion: 'Christian',
    caste: 'General',
    subCaste: 'N/A',
    education: 'Masters',
    occupation: 'Doctor',
    email: 'william.alexander@example.com',
    phone: '0987654321',
    isFavorite: true,
  ),
  User(
    name: 'Victoria Rose',
    gender: 'Female',
    dob: '1992-09-30',
    maritalStatus: 'Single',
    country: 'UK',
    state: 'England',
    city: 'London',
    religion: 'Muslim',
    caste: 'General',
    subCaste: 'N/A',
    education: 'PhD',
    occupation: 'Scientist',
    email: 'victoria.rose@example.com',
    phone: '1122334455',
    isFavorite: false,
  ),
  User(
    name: 'Michael Jordan',
    gender: 'Male',
    dob: '1988-02-20',
    maritalStatus: 'Married',
    country: 'Australia',
    state: 'Queensland',
    city: 'Brisbane',
    religion: 'Hindu',
    caste: 'OBC',
    subCaste: 'N/A',
    education: 'Masters',
    occupation: 'Teacher',
    email: 'michael.jordan@example.com',
    phone: '5566778899',
    isFavorite: true,
  ),
];
